### ISSUE TITLE
Yahoo weather service, as used in weather example, has been closed down

### ISSUE THREAD

**Issue by nickbroon** [pimoroni/breakout-garden#11]
See https://twitter.com/ydn/status/1079784441344446464 for details.

> On Jan. 3, 2019, the http://weather.yahooapis.com  and http://query.yahooapis.com  for Yahoo Weather API will be retired. Contact yahoo-weather-ydn-api@oath.com for credentials for the free Yahoo Weather API service at https://weather-ydn-yql.media.yahoo.com/forecastrss .

**Comment by sandyjmacdonald** [comment]
I believe I've got a fix for this that involves a geocode lookup to get lat/lon coordinates and then scraping the relevant bits of info from https://darksky.net/forecast/. I hope to get it implemented in the morning!

**Comment by nickbroon** [comment]
Instead of scraping darksky, perhaps this python library would be more useful?
https://github.com/AnthonyBloomer/weather-api
It can lookup based on lat/lon or location and is based on the still available yahoo weather API:
https://developer.yahoo.com/weather/documentation.html

**Comment by nickbroon** [comment]
python api for darksky: https://github.com/ZeevG/python-forecast.io

**Comment by SirLancelotDuLac** [comment]
Any of you have a working sample if this example?

**Comment by sandyjmacdonald** [comment]
Ok, should be fixed now, as per https://github.com/pimoroni/breakout-garden/pull/15
