### ISSUE TITLE
Installer failed to install five breakout boards at once

### ISSUE THREAD

**Issue by lesp** [pimoroni/breakout-garden#2]
Hello :)
==SETUP==

- Brand new Raspbian from latest image installed fresh this morning.
- Raspberry Pi 3B
- SSH in to Pi from Linux machine over Ethernet

==END==

- git clone the repo, attached five breakout boards BME680, OLED, LSM303D, BH1745, VL53L1X
- Ran the installer as per instructions.
- I2C not enabled via installer (typically Pimoroni boards have an I2C step in the installer)
- Ran sudo raspi-config and enabled I2C, rebooted for good luck.
- Ran the installer again

![breakoutgarden](https://user-images.githubusercontent.com/998860/44345004-ef799e80-a489-11e8-9f0b-8dccbc6441fc.gif)

- Received the above error message (GIF image)
- Removed four breakouts and repeated install.
- Installer detected one board and installed.
- Repeated the install process, adding a new breakout each time.
- Worked each time/
- All working.

Hope this makes sense :)
Les

**Comment by sandyjmacdonald** [comment]
The problem appears to be that the script attempts to write to a [temporary directory](https://github.com/pimoroni/breakout-garden/blob/0fbf6d193a5cf8411d7a9a5381aab047ee5ac792/install.sh#L22) that doesn't exit.

[This commit](https://github.com/pimoroni/breakout-garden/commit/28317c843bc3e6e962f49e553ee0acbcbb3f3e63) should fix the problem, by adding a `if [ ! -d "$TMP_DIR" ]; then mkdir $TMP_DIR fi` to create the temporary directory if it doesn't already exist.

**Comment by sandyjmacdonald** [comment]
Ok, it seems to work now, so closing this issue...
