### ISSUE TITLE
Error installing for mlx90640

### ISSUE THREAD

**Issue by fgarofalo56** [pimoroni/breakout-garden#24]
Warning/error when running the install script with the mlx90640.  install.log:  Warning: No install.sh found for mlx90640 thermal camera.

**Comment by Gadgetoid** [comment]
Probably need some way to pop up some kind of pointer for devices like this. There's no meaningful way for this installer to install mlx90640 since it's just a bunch of C examples and a C driver. No library per se.

**Comment by Gadgetoid** [comment]
Should be fixed with a warning and info in https://github.com/pimoroni/breakout-garden/pull/28
