### ISSUE TITLE
Incorrect identification of module

### ISSUE THREAD

**Issue by Morrolan** [pimoroni/breakout-garden#25]
The Breakout Garden installer detected my PA101D GPS module as a UV and UVA sensor.  It might be worth checking the I2C addresses of both.

breakouts.config shows I2C address of 0x10 is:  veml6075-python: veml6075: veml6075 uva and uvb sensor

However this is now the address printed on my PA1010D GPS module, which isn't listed in the breakouts.config.

**Comment by Gadgetoid** [comment]
PA1010D was never added to the list of known devices and there was no chip ID check for VEML6075, I've fixed that in #26 but there's no doubt a few more updates needed here!
