### ISSUE TITLE
ltr559 won't install 

### ISSUE THREAD

**Issue by koaning** [pimoroni/breakout-garden#8]
The `ltr559` sensor gives an install error. Figured I'd let people know about it here. 

```
pi@raspberrypi:~/breakout-garden-master $ sudo ./install.sh
Breakout Garden requires I2C. We've enabled it for you.

Breakout Garden: Installer. (3 breakout(s) found)

bme680 weather sensor:          Installed
vl53l1x time of flight:         Installed
ltr559 proximity sensor:        Error!

Installing 3 module(s). Enter to continue (Ctrl+C to cancel)...
Errors occured during install. For more info see /tmp/breakout-garden/install.log
pi@raspberrypi:~/breakout-garden-master $ cat /tmp/breakout-garden/install.log
Warning: No install.sh found for ltr559 proximity sensor.
```

Retrying doesn't help.

**Comment by Gadgetoid** [comment]
Ah looks like the repository is missing the `install.sh` and `uninstall.sh` endpoints that Breakout Garden Installer requires- https://github.com/pimoroni/ltr559-python

**Comment by Gadgetoid** [comment]
Should be fixed in - https://github.com/pimoroni/ltr559-python/commit/4d136b1fa1bed175974cc65941ae49caf2512f9d

**Comment by koaning** [comment]
It's looking green. 

```
pi@raspberrypi:~/breakout-garden-master $ sudo ./install.sh
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

Breakout Garden: Installer. (3 breakout(s) found)

bme680 weather sensor:          Installed
vl53l1x time of flight:         Installed
ltr559 proximity sensor:        Installed

Installing 2 module(s). Enter to continue (Ctrl+C to cancel)...
```

Awesome. Thanks!

**Comment by st152840** [comment]
I'm getting the same error with Thermal camera

Breakout Garden: Installer. (1 breakout(s) found)

mlx90640 thermal camera:        Error!

Installing 1 module(s). Enter to continue (Ctrl+C to cancel)...
Errors occured during install. For more info see /tmp/breakout-garden/install.log
