### ISSUE TITLE
option to install everything

### ISSUE THREAD

**Issue by koaning** [pimoroni/breakout-garden#9]
This is a feature request. 

I like being able to install all requirements remotely via something that can do parallel ssh (`ansible` in my case). The current install process seems to require that you do this step manually: 

```
pi@raspberrypi:~/breakout-garden-master $ sudo ./install.sh help
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

Breakout Garden: Installer. (3 breakout(s) found)

bme680 weather sensor:          Installed
vl53l1x time of flight:         Required
ltr559 proximity sensor:        Required

Installing 2 module(s). Enter to continue (Ctrl+C to cancel)...
```

Would it be possible to add a flag to the script such that you just install everything? It is a bit of a bother that I need to manually run a script on every device (I've got 8 in my house) whenever I add a sensor.

**Comment by Gadgetoid** [comment]
I might be 3-4 years behind the curve, but I've just started working on this.

**Comment by koaning** [comment]
It's appreciated either way 👍

**Comment by Gadgetoid** [comment]
It'll be available as soon as I merge - https://github.com/pimoroni/breakout-garden/pull/28

Though *everything* is currently everything supported by breakouts.config, might be a little out of date!
